### ISSUE TITLE
RST tables multirow cells rendering

### ISSUE THREAD

**Issue by marian-code** [pypa/readme_renderer#182]
As I understand this is the lib that powers PyPI REDME rendering so I post this question here.

## The problem

PyPI renders multirow cells in a way that it essentially ignores them which messes up the following rows. I have first encounterd this problem when trying to publish package to PyPI: https://pypi.org/project/ssh-utilities/ .

## Minimal reproducible example

```rst
+---------------+---------------+
| title1        | title2        |
+===============+===============+
| col1          | col2          |
+---------------+---------------+
| mutirow       | cell1         |
|               +---------------+
|               | cell2         |
+---------------+---------------+
| singlerow     | cell3         |
+---------------+---------------+
```

Render this rst code with `readme-renderer`

```bash
python -m readme_renderer README.rst -o README.html
```

You will get this:
![example](https://user-images.githubusercontent.com/26881798/104957140-e03a0a80-59cd-11eb-81c8-ce76db2f99d3.jpg)

In the picture you can see the **cell2** is incorrectly possitioned in the first column.

As far as I know RST is not supposed to render like this. So is this a know bug? Does any workaround exist? or is this on purpose?

**Comment by miketheman** [comment]
Reviewing older issues, this one wasn't responded to.

This does appear to be a missing part of the functionality, as [docutils supports this kind of table layout](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#tables).

It's likely due to us stripping out the necessary directives to support this view during the `clean()` phase.
I'll add some tests and figure out the necessary directives to support this.
