### ISSUE TITLE
Fix `readme` release on pypi 

### ISSUE THREAD

**Issue by ionelmc** [pypa/readme_renderer#40]
The current "fix" for #26 is not very good and creates unnecessary churn on people to switch to a new package.

A better way:

* Make an "alias package". This package will depend on `readme_renderer` but it won't install any files.
 
  Eg:

```
from setuptools import setup


setup(
    install_requires=['readme_renderer'],
    name='readme',
    platforms=['all'],
    py_modules=['wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141'], # allows empty wheel to be created
    version="0.8.0",
)  
```

**Comment by jezdez** [comment]
I didn't take your suggested approach because I assume it prevents users to see updates to `readme_renderer` when running `pip install -U readme`. I may be wrong, so I'd appreciate you double checking if this truly won't create the necessity of having to push a new version of the alias package every time `readme_renderer` is updated.

Since I didn't make the `readme` and `readme_renderer` release in a vacuum but in close discussion with @dstufft I want him to take a look at this as well.

In the meantime you can work around this by pinning readme to a version <0.7.0 in your projects.

**Comment by jezdez** [comment]
I just check myself and you're right, pip at least will successfully upgrade a dependency when calling `pip install -U <dependant>`. For some reason I assumed that would not be the case, I wonder if this was a past behavior of pip that has been fixed ever since. Either way, you strategy makes sense.

**Comment by reinout** [comment]
Readme isn't really an end-user application, more a library. And the ones that have it as a dependency are probably the more well-behaved projects, right? So I think it is good enough to just keep the current 'readme' package as-is. Only print a visible warning when installing that you ought to use `readme_renderer`.

Soon enough, those projects that have it as a dependency will use the new name. Problem solved. Reason: if you use readme, you're almost per definition a well-behaved well-maintained project.

So I don't think alias packages or new alias packages for every new release are needed. Don't make the problem bigger than it is.

(What does need fixing is the install-breaking 0.7.0: already-released packages that depend on readme cannot be retro-actively changed to depend on `< 0.7.0`. And "you can work around it" means documenting the 0.7.0 readme bug in all the projects that use it. That is pretty bad PR for readme_renderer. So please just release a 0.7.1 that doesn't do a `sys.exit(1)` )

**Comment by jezdez** [comment]
@reinout Thank you for elaborating, I agree that auto installing `readme_renderer` may be a tad too much magic. But we need to remember that it was broken completely for many people (including me) so it's still an improvement to the previous situation. In case we receive negative feedback from others depending on the readme project we can reconsider the strategy of the work around along your suggestion.

The just released 0.7.1 removed the `sys.exit` call and installs `readme_renderer` which effectively forces users switch to readme_renderer.

I'd like to point out that while we're here that the readme library was created as a support library for warehouse and never reached a stable release version. The number of feedback we received, including a bug in Python's bug tracker, led to the correct of the package name. I apologize for the inconvenience and any negative PR this may cause.

**Comment by reinout** [comment]
Auto-installing readme_renderer is fine regarding installation. I just tried it out and installing `readme` works (similarly zest.releaser).

Current versions of zest.releaser still have a problem as it cannot import `readme` anymore. So for me, it went from a working situation to a broken one (where a single `print("please switch to readme_renderer")` in the setup.py of the existing package would have been enough (and less work and simpler)).

Btw: I also get a warning when installing:

    file wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141.py (for module wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141) not found

So I guess the `MANIFEST.in` isn't correct.

Anyway, I'll just release a new zest.releaser version. It is only one utility that's broken now. It isn't core functionality.

Readme *was* advised to us as The Way Forward instead of simply using docutils. I was told that pypi itself used it, so I didn't treat it as unstable.

**Comment by dstufft** [comment]
This is mostly my fault as I told Jannis to release a readme 0.7 that had a broken ``setup.py``, so if folks want to be upset at someone, they can be upset at me.

FTR the reason I choose to break it is:

* I don't consider it stable yet, that's why it's not documented really, doesn't have a stable version number (1.x), and didn't have a change log.
* Output in ``setup.py`` is hidden unless installation fails if you're using a recent version of pip to do the install, so install time warnings won't be seen.
* We had to change the name of the import to deal with the collision of ``readme/`` and ``README`` which mandated an API break as well.

I guess I mostly didn't expect folks to be depending on anything but the ``python setup.py check -r -s`` integration (for which, switching the install name in a tox job is a trivial 2 second fix). I suppose we should bump things up to a stable version number and actually document the library.

**Comment by reinout** [comment]
I didn't know about the quietness of pip (I mostly use buildout). A quick run-time `print("please upgrade")` would have solved that, too, though.

I *did* mention in #34 that *there are other packages depending on readme now. So please don't move around the render() method too much.*

I'm not so much upset as surprised/confused. And suddenly suspicious of all my dependencies...

(Note: I've already fixed it in zest.releaser and put a comment in the changelog)
