### ISSUE TITLE
Support Syntax Highlighting w/ GFM

### ISSUE THREAD

**Issue by di** [pypa/readme_renderer#75]
From https://github.com/pypa/warehouse/issues/3508:

> GItHub has syntax highlighting for code blocks, PyPI has not.

**Comment by jonparrott** [comment]
According to https://github.com/github/markup github uses https://github.com/github/linguist#syntax-highlighting which in turn uses a series of grammars listed [here](https://github.com/github/linguist/blob/master/vendor/README.md). 

This is all in ruby so it's probably not a great idea for us to use this. We should seek some python alternatives.

**Comment by jab** [comment]
It looks like syntax highlighting isn't supported for reStructuredText either.

(For example, https://pypi.org/project/bidict/#quick-start is not currently syntax highlighted on Warehouse, despite being under a `.. code:: python` block. By contrast, https://bidict.readthedocs.io/index.html#quick-start, which is generated by Sphinx from the same source file, is.)

Was this issue meant to be limited to supporting syntax highlighting just for GFM? Seems worth doing for rST too, but there's no dedicated issue for that. Maybe this issue was misnamed and both were meant to be tracked here?

FWIW, [Pygments](http://pygments.org/) is what [Sphinx](http://www.sphinx-doc.org/) uses for syntax highlighting and it looks like it's [already a dependency](https://github.com/pypa/readme_renderer/blob/93b70a72230565b18bd621e3e61b5739b34f1527/setup.py#L67).

P.S. 👋 @jonparrott @brainwane 😊

**Comment by di** [comment]
@jab Actually, it looks like the problem is that in the source distribution you've published to PyPI as version 0.15.0, the `README.rst` does not indicate that the block is a code block:

```
Quick Start
-----------

    >>> from bidict import bidict
    >>> element_by_symbol = bidict({'H': 'hydrogen'})
    >>> element_by_symbol['H']
    'hydrogen'
    >>> element_by_symbol.inv['hydrogen']
    'H'


For more usage documentation,
head to the :doc:`intro` [#fn-intro]_
and proceed from there.
```

Looks like this changed in https://github.com/jab/bidict/commit/27f4a4f7f55a1195c201f35d6f7dc7176ce27e11 which is 19 hours old, while the last `bidict` release was on Mar 29, 2018.

I think if you make a new release of bidict, your code blocks will be correctly syntax highlighted.

**Comment by jab** [comment]
Indeed, that [fixed it](https://pypi.org/project/bidict/#quick-start). Thank you @di and sorry I missed that!

Actually, would it make sense for Warehouse to assume Python syntax highlighting for code blocks that don't specify a language? That seems to be what Sphinx does. And since Sphinx is what many (most?) Python projects use for documentation, maybe a lot of other projects don't know they need to add the explicit `.. code-block:: python` to get syntax highlighting to work elsewhere?

**Comment by di** [comment]
@jab Glad to hear it.

With regards to rST, this module is essentially just a wrapper around `docutils`, so that would likely be the right place to address it, not in `warehouse` or `readme_renderer` (unless it's as simple as a configuration change).

**Comment by jab** [comment]
From http://docutils.sourceforge.net/sandbox/code-block-directive/docs/syntax-highlight.html it looks like this can be done with `.. default-literal-block::  code-block python`. (I didn't immediately see a way to set this programmatically from docutils client code, but I only had a few minutes to look.) I understandd if this is out of scope for readme_renderer. Thanks again for discussing!
