### ISSUE TITLE
Challenging render performance

### ISSUE THREAD

**Issue by ewdurbin** [pypa/readme_renderer#95]
Noted via pypi.org error logs. Also exhibited on legacy pypi... so pretty sure it's readme_renderer.

https://gitlab.com/hansroh/skitai/blob/master/README.rst chokes out performance and leads to timeouts. Not sure there's a whole lot we can easily do but figured it's worth noting.

**Comment by ewdurbin** [comment]
FWIW Gitlab's UI also seems to have a bit of a challenge rendering :)

**Comment by jonparrott** [comment]
Holy cow that is a beastly README. 

What is expected of `readme_renderer` here? Our `rst` rendering is a relatively small layer on top of `docutils` so I'm not sure what we can do in terms of performance tuning.

**Comment by ewdurbin** [comment]
No particular call to action. Opened this issue as a place to discuss and see if we have any options.

FWIW since descriptions are not editable we do have the option of only invoking readme_renderer once in warehouse and stashing the result... only downside is improvements to the library wouldn't be realized without invalidation/rerender :/

**Comment by miketheman** [comment]
Revisiting this, since it's the oldest open issue,

The source repo has moved to a Markdown-based readme, starting in https://gitlab.com/skitai/skitai/-/commit/600bd6d53d9bd757aa3d9d7c7425671710bbab8a and has removed the lengthy RST file in https://gitlab.com/skitai/skitai/-/commit/6238d6daaa4368892cfa16c5705787e3908d26de#561b88e19de321ca62c7590bbb350765fb110905
The final version can be found at this commit: https://gitlab.com/skitai/skitai/-/blob/9401c8e7d5c2b5e85c6700e1d8ec915c19901de5/README.rst

While they have removed if from their project, it still serves as a good example for a "heavy" RST file, clocking in a ~94Kb.

Using a GitPod instance (Cloud-based Linux container, 16 CPUs, 64GB RAM), docutils 0.18.1

To measure on a bunch of different permutations, I installed the current version of `readme_renderer` in each Python version, having installed the most recent release of each via pyenv:

```shell
for i in 3.7 3.8 3.9 3.10; do python$i setup.py develop; done
```

Once installed, I used https://github.com/sharkdp/hyperfine to benchmark across all variations using the `README.rst` I'd downloaded from gitlab.

```shell
hyperfine --warmup 2 -L pyver 3.7,3.8,3.9,3.10 'python{pyver} -m readme_renderer -o /dev/null tests/README.rst'
```
This runs the test command twice to warm up the system, in case there's any compilation steps, disk allocations, etc.
Then it runs the command 10 times and collects results.

The results:

```
Benchmark 1: python3.7 -m readme_renderer -o /dev/null tests/README.rst
  Time (mean ± σ):      1.860 s ±  0.027 s    [User: 1.809 s, System: 0.055 s]
  Range (min … max):    1.825 s …  1.908 s    10 runs
 
Benchmark 2: python3.8 -m readme_renderer -o /dev/null tests/README.rst
  Time (mean ± σ):      1.772 s ±  0.034 s    [User: 1.728 s, System: 0.048 s]
  Range (min … max):    1.712 s …  1.820 s    10 runs
 
Benchmark 3: python3.9 -m readme_renderer -o /dev/null tests/README.rst
  Time (mean ± σ):      1.762 s ±  0.021 s    [User: 1.714 s, System: 0.052 s]
  Range (min … max):    1.735 s …  1.794 s    10 runs
 
Benchmark 4: python3.10 -m readme_renderer -o /dev/null tests/README.rst
  Time (mean ± σ):      1.819 s ±  0.025 s    [User: 1.769 s, System: 0.053 s]
  Range (min … max):    1.792 s …  1.860 s    10 runs
 
Summary
  'python3.9 -m readme_renderer -o /dev/null tests/README.rst' ran
    1.01 ± 0.02 times faster than 'python3.8 -m readme_renderer -o /dev/null tests/README.rst'
    1.03 ± 0.02 times faster than 'python3.10 -m readme_renderer -o /dev/null tests/README.rst'
    1.06 ± 0.02 times faster than 'python3.7 -m readme_renderer -o /dev/null tests/README.rst'
```
There's very little variance between Python versions tested.

Overall, the maximum runtime is under 2 seconds - is that lower than the timeouts originally perceived?

Or is under 2 seconds an acceptable timing, and this can be closed out?

**Comment by miketheman** [comment]
@ewdurbin Curious if there’s timings on render performance now that the transformation happens on upload from https://github.com/pypi/warehouse/pull/5818 or of this is acceptable and can be closed?

**Comment by ewdurbin** [comment]
Yes! This is acceptable.
